global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 60s


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    honor_labels: true
    honor_timestamps: true
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sensors-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8282']
